use axum::{
    extract::{State, Query},
    http::{HeaderMap, StatusCode},
    Json,
};
use mongodb::{Database, bson::doc};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::time::Duration;
use futures::stream::StreamExt;

use crate::services::bulk_translate::bulk_translate_all_content;
use crate::services::translation_service::{
    bulk_translate, check_rate_limit, get_translation, normalize_lang, IpRateLimit,
};

use crate::config::languages::get_supported_languages;
use crate::util::http::client_ip;
use crate::models::cms::CMSItem;
use crate::models::blog::Blog;
use crate::models::news::News;
use crate::models::course::Course;
use crate::models::course_category::CourseCategory;

#[derive(Debug, Deserialize)]
pub struct ContentQuery {
    pub lang: Option<String>,
}

use std::collections::HashMap;

#[derive(Debug, Serialize)]
pub struct TranslatedContentResponse {
    pub cms: Vec<CMSItem>,
    pub blogs: Vec<Blog>,
    pub news: Vec<News>,
    pub courses: Vec<Course>,
    pub categories: Vec<CourseCategory>,
    pub static_texts: HashMap<String, String>,
}

pub async fn admin_bulk_translate(
    State(db): State<Database>,
) -> (StatusCode, Json<Value>) {
    bulk_translate_all_content(&db).await;
    (
        StatusCode::OK,
        Json(serde_json::json!({
            "success": true,
            "message": "Bulk translation started"
        })),
    )
}

pub async fn get_translated_content(
    State(db): State<Database>,
    Query(q): Query<ContentQuery>,
) -> (StatusCode, Json<TranslatedContentResponse>) {
    let lang = normalize_lang(&q.lang.unwrap_or_else(|| "en".to_string()));
    
    // 0. Fetch Static Texts
    let mut static_texts = HashMap::new();
    let static_keys = vec![
        "Welcome to CodeArya",
        "Start your journey",
        "Contact us",
        "Build Your Future with",
        "IT & Skill Education",
        "Empowering students with industry-ready skills through certified computer courses and vocational training programs.",
        "Powered by CodeArya",
        "All Rights Reserved",
        "Industry Insights",
        "For Future Professionals",
        "Knowledge Center",
        "Explore All Articles",
        "Featured Article",
        "Career Growth",
        "Web Development Roadmap for Students",
        "Design Industry",
        "Read More",
        "Quick Links",
        "Support",
        "Follow Us",
        "Why Choose Us",
        "We Don’t Just Teach —",
        "We Build Careers",
        "Our mission is to provide practical knowledge, industry exposure, and complete placement support so students can confidently enter the competitive job market.",
        "Real-world project based training instead of only theoretical classes.",
        "Dedicated placement cell with interview preparation & resume guidance.",
        "Updated curriculum aligned with current industry tools & technologies.",
        "Personalized mentoring and doubt-clearing support throughout the course.",
        "Explore Courses",
        "Certified Courses",
        "Industry-recognized certifications that boost your resume and career.",
        "Expert Faculty",
        "Experienced trainers with real industry exposure and teaching excellence.",
        "Practical Training",
        "Hands-on lab sessions with real-world projects and assignments.",
        "Updated Curriculum",
        "Regularly updated syllabus aligned with current industry demands.",
        "Placement Support",
        "100% placement assistance with interview prep and job referrals.",
        "Modern Infrastructure",
        "AC labs, high-speed internet, and latest software tools.",
        "Meet Our Expert Trainers",
        "Our experienced faculty members bring real industry knowledge and practical expertise to ensure students receive career-focused training.",
        "Our Faculty",
        "How to Join",
        "Admission Process",
        "Enquiry",
        "Fill the enquiry form or visit our center for counseling.",
        "Counseling",
        "Get personalized course guidance based on your goals.",
        "Enrollment",
        "Complete admission formalities and start your journey.",
        "Exam",
        "Appear for regular assessments and final examinations.",
        "Certification",
        "Complete your course and receive industry-recognized certificate.",
        "Step",
        "Sir Chhotu Ram Education Pvt. Ltd.",
        "IT & Skill Education",
        "Empowering students with industry-ready IT skills and vocational training for a brighter future.",
        "Home",
        "About",
        "Courses",
        "Franchise",
        "Student Zone",
        "Gallery",
        "Blog",
        "Downloads",
        "FAQ",
        "Shop",
        "Contact",
        "Dashboard",
        "Overview",
        "Revenue Summary",
        "Center Statistics",
        "Activity Logs",
        "CRM",
        "Enquiries",
        "Enquiry Pipeline",
        "Follow-up Reminders",
        "Student Leads",
        "Franchise Leads",
        "General Leads",
        "CMS",
        "Pages",
        "Slider",
        "Gallery",
        "Teachers",
        "Partners",
        "Downloads",
        "Verification Page",
        "Ticker",
        "Blogs",
        "News",
        "Admins Management",
        "Add New Admin",
        "Admin List",
        "Today's Stats",
        "Recent Activity",
        "My Center Profile",
        "Request Profile Update",
        "Certificate Assets",
        "Attendance",
        "Attendance Register",
        "Monthly Report",
        "Centers",
        "All Centers",
        "Add New Center",
        "Center Requests",
        "Franchise Fees",
        "Center Wallets",
        "Manage Locations",
        "Recycle Bin",
        "Students",
        "All Students",
        "Approvals",
        "Student Certificates",
        "Certificate Approvals",
        "Document Requests",
        "Enrollment Reports",
        "Add Student",
        "Student Fees",
        "Apply Certificates",
        "Issue certificates",
        "Issue marksheets",
        "Live Classes",
        "Schedule Class",
        "Class History",
        "New Enquiries",
        "Follow-ups",
        "Converted Leads",
        "Internal Messages",
        "Center Announcements",
        "Academics",
        "Course Categories",
        "Courses",
        "Subjects",
        "Question Bank",
        "Subject Mapping",
        "Sessions",
        "Study Material",
        "Exam Blueprints",
        "Mock Tests",
        "Exam Engine V2",
        "Question Feedback",
        "Allotted Courses",
        "Course Subjects",
        "Course Materials",
        "Typing Master",
        "Languages",
        "Lessons",
        "Typing Analytics",
        "Tests & Allotment",
        "Global Reports",
        "Student Reports",
        "Center Leaderboard",
        "Practice Now",
        "My History",
        "Leaderboard",
        "Exams",
        "Allot Exam",
        "Exam Papers",
        "Exam Results",
        "Exam V2 (Center)",
        "Practicals",
        "All Practicals",
        "Create Practical",
        "Submissions",
        "Finance",
        "Wallet Management",
        "Transactions",
        "Commission Reports",
        "Franchise Payments",
        "Wallet",
        "My Balance",
        "Payment History",
        "Progress Summary",
        "My Course",
        "Enrolled Course",
        "My Subjects",
        "Recorded Classes",
        "Join Class",
        "Class Schedule",
        "Assigned Practicals",
        "Submit Practical",
        "Submission History",
        "My Attendance",
        "Attendance Report",
        "Certificates",
        "My Certificates",
        "Download Certificate",
        "My Exams",
        "Pending Exams",
        "Payments",
        "Fee Details",
        "Notifications",
        "Announcements",
        "Messages",
        "Review Us",
        "Attachments",
        "Certificate templates",
        "Marksheet templates",
        "ID card template (design)",
        "Template designer",
        "Staff Management",
        "Add New Staff",
        "Logout",
        "Staff List",
        "System",
        "Login",
        "Welcome",
        "language",
        "login",
        "logout",
        "welcome",
        "Center Management",
         "Enroll Student",
         "Enroll New Student",
         "Comprehensive student registration for certificates and system access.",
         "Personal Information",
         "Personal Mobile No.",
         "Course Enrollment",
         "Father's Name",
         "Mother's Name",
         "Date of Birth",
         "Category",
         "Government ID Type",
         "Government ID Number",
         "Academic & Professional Details",
         "Enrollment Number",
         "Roll Number",
         "Session From",
         "Session To",
         "Location & Address Details",
         "Emergency & Documents",
         "Student Photo",
         "Academic & Identity Documents",
         "Portal Access",
         "Complete Enrollment",
         "10th DMC",
         "Government ID Image",
         "Student Signature",
         "Other Document (Manual)",
         "What document it is?",
         "Upload Photo",
         "Upload 10th DMC",
         "Upload Government ID Image",
         "Upload Signature",
         "CMS Management",
         "Control all dynamic content across the SCRE platform.",
         "Pages",
         "Hero Slider",
         "Gallery",
         "Teachers",
         "Partners",
         "Downloads",
         "Download Categories",
         "Verification",
         "Ticker",
         "FAQ",
         "ID Card Templates",
         "Active System Users",
         "Inactive System Users",
         "All System Users",
         "Manage user accounts, roles, and access status across the entire platform.",
         "SEARCH BY USERNAME OR ROLE...",
         "User Directory",
         "Account Information",
         "Access Level",
         "Joined Date",
         "Current Status",
         "Action",
         "Reset Password",
         "New Password",
         "Confirm Reset",
         "Cancel",
         "Failed to load centers",
         "An error occurred while loading data",
         "Failed to load center assets",
         "ARE YOU SURE YOU WANT TO MOVE THIS CENTER TO THE RECYCLE BIN? This will stop all systems, students, and user accounts for this center.",
         "Center moved to Recycle Bin",
         "Failed to move center to bin",
         "Failed to generate PDF",
         "An error occurred during printing",
         "Center updated successfully",
         "Update failed",
         "File uploaded",
         "Upload failed",
         "Today's Stats",
         "Today's Collection",
         "Today's Attendance",
         "Total Students",
         "transactions",
         "Attendance",
         "Action Required",
         "Total Admins",
         "Active Centers",
         "Total Students",
         "Revenue",
         "Operational",
         "Active Students",
         "Registered",
         "Active Announcements",
         "Live notices",
         "Uptime",
         "System Healthy",
         "Super Admin",
         "Super Admin Overview",
         "Global system activity and live performance metrics.",
         "System Live: 99.9% Uptime",
         "Live User Activity",
         "users",
         "System Active",
         "All System Users",
         "Search users...",
         "User",
         "Role",
         "Joined",
         "Status",
         "Action",
         "Inactive",
         "Disk Usage",
         "Database",
         "Media Assets",
         "System Alerts",
         "Database backup pending for over 24 hours.",
         "3 Centers subscriptions expiring this week.",
         "Failed to fetch revenue data",
         "Date",
         "Receipt",
         "Center",
         "Student",
         "Mode",
         "Amount",
         "Unknown",
         "Revenue Summary",
         "Financial performance tracking across centers",
         "Export Report",
         "Start Date",
         "End Date",
         "Filter by Center",
         "ALL CENTERS",
         "Quick Search",
         "RECEIPT, STUDENT...",
         "Calculating Revenue Data...",
         "Total Revenue",
         "Transactions",
         "Avg / Transaction",
         "Revenue Breakdown",
         "Receipt No",
         "Authorized Center",
         "Guest Student",
         "No revenue records found for this period",
         "Try adjusting your filters or search query",
         "Center Statistics",
         "Fee collection and activity by center.",
         "Center-wise Collection",
         "No data yet.",
         "Recent Activity",
         "Latest fee collections and attendance.",
         "Activity Feed",
         "No recent activity.",
         "Fee collected: ₹{{amount}} ({{receipt}})",
         "Attendance marked",
         "Absent recorded",
         "My Center Profile",
         "Your center details as configured by admin.",
         "Loading…",
         "No center profile found for this login.",
         "Center Overview",
         "Code",
         "Suspended",
         "Owner",
         "Phone",
         "Email",
         "Open Map",
         "About Center",
         "Validity & Hours",
         "Validity",
         "Working Hours",
         "Days",
         "Infrastructure & Compliance",
         "Computers",
         "Classrooms",
         "Staff",
         "Lab Type",
         "Internet",
         "Power Backup",
         "Yes",
         "No",
         "Courses Allotted",
         "No courses allotted.",
         "Gallery",
         "No gallery images uploaded.",
         "Failed to load admin directory",
         "Are you sure you want to delete this admin account? This action cannot be undone.",
         "Admin deleted successfully",
         "Failed to delete admin",
         "An error occurred while deleting admin",
         "Status toggle is being initialized...",
         "Role updated",
         "Failed to update role",
         "Admin Directory",
         "Manage regional administrators and their system access privileges.",
         "Add New Admin",
         "SEARCH BY USERNAME...",
         "Filter Results",
         "System Administrators",
         "Retrieving Secure Data...",
         "No administrators found.",
         "Admin Identity",
         "Access Level",
         "Creation Date",
         "Status",
         "Management",
         "admin",
         "center",
         "student",
         "Saving…",
         "Save",
         "Enabled",
         "Disabled",
         "Live Status",
         "Operations Checklist",
         "Active Session",
         "Student Registrations",
         "{{count}} total students enrolled",
         "Course Management",
         "{{count}} active courses authorized",
         "Pending Enquiries",
         "{{count}} new leads need follow-up",
         "Up to date",
         "Examination Grading",
         "{{count}} submitted exams need grading",
         "Evaluate Now",
         "All Graded",
         "Live Exam Monitoring",
         "{{count}} students currently taking exams",
         "Real-time",
         "Academic Excellence",
         "N/A",
         "Score",
         "No recent records found",
         "Admin",
         "Notices",
         "CRM Status",
         "New",
         "Contacted",
         "Follow-up",
         "Converted",
         "Lost",
         "Enquiry Performance",
         "Student Performance",
          "Loading locations...",
          "Locations",
          "Add a country first, then open it to add states, cities, and areas. Use bulk paste (one name per line, or comma / semicolon separated) to load many at once.",
          "Seed India + states",
          "Countries",
          "Country name",
          "Code (optional, e.g. IN)",
          "Add country",
          "No countries yet. Add one or use \"Seed India\".",
          "States",
          "Select a country to manage states.",
          "State name",
          "Add state",
          "Bulk: one state per line, or separate with commas / semicolons",
          "Add bulk states",
          "No states for this country.",
          "Cities",
          "Select a state to manage cities.",
          "City name",
          "Add city",
          "Bulk cities (lines or commas)",
          "Add bulk cities",
          "No cities for this state.",
          "Areas / localities",
          "Select a city to manage areas (sectors, localities).",
          "Area or locality",
          "Add area",
          "Bulk areas (lines or commas)",
          "Add bulk areas",
          "No areas for this city.",
          "Center addresses",
          "can later be wired to pick from this master data; today centers still use free-text city/state fields.",
          "System Settings",
           "Language changed successfully",
           "Settings saved successfully",
           "Configure your account preferences and notification controls.",
           "Security & Password",
           "New Password",
           "Confirm Password",
           "System Preferences",
           "Email Notifications",
           "Receive alerts about center activities.",
           "Interface Language",
           "System default is English (International).",
           "Save All Settings",
           "Shop Management",
        "Role Permissions",
        "Translation Usage",
        "Notification Settings",
        "Disk & Storage",
        "Admin Certificate Assets",
         "Maintenance",
         "Report Question Issue",
         "Feedback Type",
         "Incorrect Question/Options",
         "Spelling/Grammar Errors",
         "General Suggestion",
         "Other Issues",
         "Describe the Issue",
         "What's wrong with this question?",
         "Cancel",
         "Submit Report",
         "Attendance Register",
         "Mark and manage student attendance for your center.",
         "Search students...",
         "Save All",
         "Student Name",
         "ID / Username",
         "Status",
         "No students found",
         "Latest News",
         "Updates and announcements from our organization.",
         "SEARCH NEWS...",
         "All Categories",
         "Updates",
         "Events",
         "Press",
         "Per Page",
         "Export CSV",
         "No news found",
         "Previous",
         "Next",
         "Knowledge & Updates",
         "Our Blog",
         "Insights, updates, and stories from our education community.",
         "SEARCH BLOGS...",
         "Featured",
         "Continue Reading",
         "Read article",
         "No more articles",
         "Search articles",
         "Search topics...",
         "Categories",
         "Trending Topics",
         "Never miss an update",
         "Enter your email",
         "Subscribe",
         "Get curated updates, career tips & course announcements.",
         "Design Exam Blueprint",
         "Exam Name",
         "e.g. ADCA Final Exam 2026",
         "Target Course",
         "Select Course",
         "Question Bank",
         "Select Bank",
         "Blueprint Mode",
         "Strict (Fail if pool low)",
         "Flex (Allow fallback)",
         "Start Window (Date & Time)",
         "Pick date & time",
         "Start time cannot be in the past (Server IST Time).",
         "Duration (Minutes)",
         "End Window (Auto-calculated)",
         "Calculated from Start + Duration",
         "Max Attempts",
         "Total Exam Marks",
         "Exam Instructions (Optional)",
         "Describe guidelines for students before they start the exam...",
         "Question Distribution",
         "Add Rule",
         "Marks per Q",
         "Question Count",
         "Exam Allotment",
         "Generate and assign exam papers to students based on blueprints",
         "Configure Allotment",
         "Select Category",
         "All Courses",
         "Select Blueprint",
         "No blueprints found for this course",
         "Target Student(s)",
         "ALL STUDENTS IN COURSE",
         "Targeting {{count}} students matching the selected course",
        "Quick Links",
        "Add Quick Link",
        "Search links...",
        "Total Centers",
        "Total Students",
        "Total Revenue",
        "Active Announcements",
        "Active Exams",
        "Pending Evaluations",
        "Total Evaluated",
        "Recent Activity",
        "View All Logs",
        "Recent Centers",
        "View All Centers",
        "CRM Status",
        "New",
        "Contacted",
        "Follow-up",
        "Converted",
        "Lost",
        "Enquiry Performance",
        "Student Performance",
        "Passed",
        "Failed",
        "Total Enquiries",
        "Today's Leads",
        "Converted Students",
        "Active Centers",
        "Total Revenue",
        "Center Wallets",
        "Staff List",
        "Profile",
        "Account Management",
        "My Profile",
        "Settings",
        "Privacy",
        "logout",
        "Appearance",
        "Select Theme",
        "Workspace",
        "Search portal records, students, or settings...",
        "Auto",
        "Light",
        "Dark",
        "System",
        "Popular Courses",
        "DCA",
        "ADCA",
        "Tally with GST",
        "Web Designing",
        "Graphic Designing",
        "Spoken English",
        "© 2026 Sir Chhotu Ram Education Pvt. Ltd. All rights reserved.",
        "About Us",
        "Shaping Futures Since Day One",
        "Who We Are",
        "is a premier institute dedicated to providing quality computer education and skill development training. We bridge the gap between education and employment through industry-relevant courses.",
        "With 10+ years of experience, 5000+ trained students, and a 95% placement rate, we are the most trusted IT training institute in the region.",
        "Government Recognized",
        "ISO Certified",
        "Experienced Faculty",
        "Modern Labs",
        "Years Experience",
        "Students Trained",
        "Placement Rate",
        "Courses Available",
        "Our Mission",
        "To empower youth with practical IT skills and vocational training that leads to employment and entrepreneurship.",
        "Our Vision",
        "To become the most trusted skill development institute producing industry-ready professionals.",
        "Our Values",
        "Quality education, student-first approach, industry partnerships, and commitment to excellence.",
        "🎓 Admissions Open 2026",
        "Apply Now — It's Free",
        "5000+ Alumni",
        "100% Placement",
        "Industry Recognized",
        "About SCRE",
        "Education That transforms Into Careers",
        "For over a decade, SCRE has empowered students with practical, industry-aligned learning experiences that translate into real professional success.",
        "Begin Your Journey",
        "Our Journey",
        "Established",
        "Expansion of Academic Network",
        "Built a strong franchise ecosystem ensuring standardized quality education.",
        "Placement-Driven Curriculum",
        "Introduced industry-aligned programs with real-world project training.",
        "Digital Transformation",
        "Integrated modern tools, labs, and digital infrastructure for advanced learning.",
        "Founded with a mission to bridge the gap between academic education and industry demand, SCRE has evolved into a trusted institution offering professional courses in technology, design, finance, and skill development.",
        "Our commitment to structured training, standardized curriculum, and placement-focused learning has helped thousands of students build sustainable careers.",
        "We continuously upgrade our academic framework to align with global digital transformation trends.",
        "Message From The Director",
        "“Our vision has always been to create a skill-driven ecosystem where students are not only educated but professionally prepared to thrive in competitive industries. At SCRE, we believe that true learning goes beyond textbooks — it requires practical exposure, discipline, adaptability, and a deep understanding of industry expectations.”",
        "We remain committed to innovation, continuous improvement, and maintaining the highest standards of educational excellence across all our centers.",
        "Director, SCRE Pvt. Ltd.",
        "Recognitions & Certifications",
        "Trusted. Verified.",
        "Recognized.",
        "Our certifications and registrations reflect our commitment to quality, compliance, and consistent learning standards across all centers.",
        "MSME Registered",
        "Officially recognized under MSME for trusted operations and verified institution identity.",
        "Company Act 2013 Registered",
        "Registered as a compliant organization with verified legal structure and credibility.",
        "Quality standards aligned to ensure structured training and consistent outcomes.",
        "Get In Touch",
        "Contact Us / Enquiry Form",
        "Send Us Your Enquiry",
        "Thank you! We'll contact you soon.",
        "Your Full Name",
        "Phone Number",
        "Email Address (Optional)",
        "Select Course",
        "Search center by name or code...",
        "Select Center (Admin Default)",
        "Your Message (Optional)",
        "Submitting...",
        "Submit Enquiry",
        "Contact Information",
        "Phone",
        "Email",
        "Address",
        "Location Map",
        "Industry Ready Skill",
        "Computer Programs",
        "Previous courses",
        "Next courses",
        "No courses published yet. Add courses in the admin dashboard.",
        "View Details",
        "View All Courses",
        "Search & Filter",
        "results",
        "Search courses...",
        "Clear search",
        "Categories",
        "All",
        "Sort By",
        "Sort",
        "Recommended",
        "Price: Low to High",
        "Price: High to Low",
        "Duration",
        "Reset Filters",
        "An ISO 9001-2015 Certified Organization",
        "Registered Under The Company ACT 2013 By The Ministry Of Corporate Affairs",
        "Ministry of Micro, Small & Medium Enterprises,",
        "Government of India",
        "Enquiry Now",
        "Verification Letter",
        "Franchise Opportunity",
        "Apply Franchise",
        "Franchise Login",
        "Support System",
        "Our Partners",
        "Franchise Requirements",
        "Why us",
        "Centers",
        "Student Login",
        "Student Registration",
        "Student Internship",
        "Student Inquiry",
        "Web Development",
        "Graphic Design",
        "Digital Marketing",
        "Office Automation",
        "Hardware & AI",
        "Business Admin",
        "Industry Mentors",
        "Live Projects",
        "Stipend-based",
        "Placement Support",
        "Launch Your Professional Career with SCREduc",
        "Join our hands-on internship program designed for Tier 2 and Tier 3 city students. Gain real-world experience, build your portfolio, and get certified by industry leaders.",
        "Why Choose SCREduc Internship?",
        "Bridge the gap between academic learning and industry requirements with our structured 3-6 month programs.",
        "Explore Our Internship Domains",
        "Inquire More",
        "Our Selection Process",
        "Online Application",
        "Fill the form with your interest area and skills.",
        "Technical Interview",
        "A short discussion about your goals and technical knowledge.",
        "Onboarding",
        "Join the team, get your mentor, and start working!",
        "Internship Outcomes",
        "What You Take Home",
        "Our program isn't just about a certificate; it's about making you \"Job-Ready\" for the competitive IT market.",
        "SCREduc Certified Professional Internship Certificate",
        "Letter of Recommendation (LOR) for top performers",
        "Portfolio of 2-3 Live Projects",
        "Confidence to handle professional client requirements",
        "Soft skills training and interview preparation",
        "Sunil Kumar",
        "Web Dev Intern, 2025",
        "Interns Trained",
        "Registration Successful!",
        "Thank you for enrolling. Your application has been received and our center will contact you shortly to complete the process.",
        "Return to Home",
        "SCRE Admissions 2026",
        "Start Your Learning",
        "Journey Today",
        "Unlock your potential with career-focused learning, industry-recognized certifications, and hands-on job skills training.",
        "Enroll Now",
        "Select Your Course",
        "Choose the program that best fits your career goals",
        "Registration Fee",
        "Personal Information",
        "Let's start with your basic details",
        "Full Name",
        "Enter your full name",
        "Father's Name",
        "Enter father's name",
        "Mother's Name",
        "Enter mother's name",
        "Email Address",
        "Resend",
        "Verify Email",
        "Verified",
        "Enter OTP",
        "Verification code sent to your email",
        "Mobile Number",
        "10-digit mobile number",
        "Date of Birth",
        "Gender",
        "Select gender",
        "Male",
        "Female",
        "Category (Caste)",
        "Select category",
        "General",
        "OBC",
        "SC",
        "ST",
        "Specify Category",
        "Government ID Type",
        "Select ID Type",
        "Passport",
        "Aadhaar Card",
        "Government ID Card",
        "Driving License",
        "PAN Card",
        "Voter ID",
        "Specify ID Type",
        "Government ID Number",
        "Enter your ID number",
        "Address Details",
        "Provide your current location for center assignment",
        "Country, State, City, Street / Locality, Area",
        "City",
        "Enter your city",
        "State",
        "Enter your state",
        "Country",
        "Enter your country",
        "Postal Code",
        "Postal / ZIP code",
        "Other Address Details",
        "Any other details",
        "Academic Background",
        "Help us understand your education",
        "Highest Qualification",
        "Select qualification",
        "10th Pass",
        "12th Pass",
        "Undergraduate",
        "Graduate",
        "Post Graduate",
        "Selected Course",
        "Change",
        "Training Center",
        "Choose nearest center",
        "Final Preferences",
        "Just a few more things to finish",
        "Batch Preference",
        "Morning",
        "Evening",
        "Learning Mode",
        "Offline (Classroom)",
        "Online (Live)",
        "Required Documents (Optional)",
        "Student Photo",
        "JPG, PNG (Max 2MB)",
        "ID Proof",
        "PDF, JPG (Max 5MB)",
        "Other Document (Optional)",
        "What document it is?",
        "Upload",
        "Course Fee",
        "Total Payable Now",
        "Back",
        "Continue",
        "Processing...",
        "Complete Registration",
        "Students",
        "Placement",
        "Certified",
        "Recognized",
        "Verified Training",
        "ISO certified curriculum and industry-standard training modules.",
        "Expert Mentors",
        "Learn from professionals with years of real-world experience.",
        "Career Support",
        "100% placement assistance and interview preparation.",
        "Expert Guidance",
        "Not Sure Which",
        "Course to Choose?",
        "Stop guessing. Get free, personalized career counseling from our industry experts today.",
        "Get Free Consultation",
        "Free Counseling",
        "One-on-one session with our experts to understand your interests and strengths.",
        "Course Guidance",
        "Detailed breakdown of modules, projects, and learning outcomes for every course.",
        "Career Advice",
        "Learn about job market trends, salary expectations, and placement opportunities.",
        "Ready to take the first step?",
        "Fill in this short form and we'll handle the rest. No commitment required, just professional advice.",
        "Response within 24 business hours",
        "Personalized roadmap based on your goals",
        "No spam, only valuable information",
        "Trusted by 5000+ students across the country",
        "Request a Call Back",
        "Your Name",
        "10-digit mobile",
        "City / Town",
        "Course Interest",
        "Select interested course",
        "Nearest Center",
        "Select training center",
        "Talk to you soon!",
        "Our expert counselor will contact you within 24 hours to provide the guidance you need.",
        "Back to Inquiry",
        "Common Questions",
        "Quick answers to things you might be wondering about",
        "Build Your Own IT Education Empire",
        "Join India's most innovative franchise network. We provide the tech, the brand, and the blueprint—you lead the growth in your city.",
        "Now Partnering for 2026-27",
        "Why Entrepreneurs Choose Us",
        "We don't just sell franchises; we build long-term partnerships that prioritize your growth and local impact.",
        "Proven Business Model",
        "Skip the trial-and-error. Our system is built on years of successful center operations.",
        "Premium Branding",
        "Leverage a recognized name in IT education that parents and students already trust.",
        "Low Capital Entry",
        "Start with a minimal investment while maximizing your local market reach.",
        "Everything You Need to Succeed",
        "From tech infrastructure to course materials, we've got you covered every step of the way.",
        "Cloud-Based ERP",
        "Manage admissions, fees, attendance, and exams with our powerful automation suite.",
        "Modern Curriculum",
        "Access 100+ industry-aligned courses ranging from basic IT to advanced AI.",
        "Marketing Kit",
        "Full set of digital and print assets to launch your center with maximum impact.",
        "Operational Support",
        "Dedicated account managers to help you scale and solve day-to-day challenges.",
        "Projected Earning Potential",
        "A transparent look at how our centers generate consistent, scalable revenue.",
        "Sample Monthly ROI",
        "Based on a Standard Center model with 100 active students.",
        "Course Fees Revenue",
        "Exam & Cert Fees",
        "Book & Kit Sales",
        "Gross Profit",
        "High Growth, Low Royalty",
        "Unlike other networks, we believe in keeping our franchise owners profitable. Our royalty structure is the most competitive in the industry.",
        "View Detailed Investment Plans",
        "Your Journey to Leadership",
        "Our streamlined onboarding process gets your center up and running in as little as 30 days.",
        "Submit Inquiry",
        "Initial Consultation",
        "Center Setup",
        "Launch & Scale",
        "Strategic Alliances for Your Success",
        "We partner with the world's leading organizations to give your center a competitive edge and your students global recognition.",
        "Our Global Ecosystem",
        "Trust & Credibility",
        "SCREduc is backed by industry-standard certifications that validate our commitment to quality IT education.",
        "Valid Certifications",
        "Every certificate issued by your center is backed by our ISO and MSME registrations.",
        "Industry Standard",
        "Our curriculum follows the latest NSQF guidelines for skill-based education.",
        "Pan-India Network",
        "Join a network that is recognized by recruiters and companies across the country.",
        "Government Accreditations",
        "Our certifications and registrations ensure that your center operates under valid legal frameworks and provides recognized diplomas.",
        "Technology Partners",
        "We collaborate with global tech giants to provide authentic software access and industry-aligned technical training materials.",
        "Become a Strategic Partner",
        "Are you a technology provider or education board looking to expand your reach? Let's collaborate to build the future of IT education.",
        "Propose Partnership",
        "What You Need to Get Started",
        "A clear roadmap of the physical and financial assets required to launch a premium SCRE center in your city.",
        "Ready to Launch Checklist",
        "Prerequisites for Success",
        "To ensure the highest standard of technical education, SCRE maintains strict quality guidelines for all training centers.",
        "Minimum Space",
        "500-1000 Sq. Ft. built-up area at a prime location in the city.",
        "Computer Lab",
        "Minimum 5-10 latest configuration systems with internet connectivity.",
        "Classroom",
        "Dedicated theory classroom with comfortable seating and board.",
        "Front Office",
        "Reception area with branding and student inquiry desk.",
        "Faculty",
        "Trained and certified instructors for respective courses.",
        "Electricity",
        "Reliable power backup (UPS/Inverter) for uninterrupted learning.",
        "Financial Investment",
        "Starting an IT center requires capital for setup, branding, and initial marketing. We offer three flexible models to suit your budget.",
        "Transparent",
        "Budgeting",
        "Basic Model (Village)",
        "Standard Model (Town)",
        "Typing Master",
        "Improve your typing speed and accuracy with guided lessons.",
        "Lessons & Tests",
        "Competition Leaderboard",
        "Personal Analytics",
        "CHOOSE LANGUAGE",
        "Select a language to see lessons",
        "No lessons found for this language",
        "beginner",
        "intermediate",
        "advanced",
        "WPM",
        "Start Practice",
        "Live Speed",
        "Accuracy",
        "Characters",
        "Target",
        "Start typing the text above...",
        "Click here to Type",
        "Reset Session",
        "Session Completed!",
        "Requirements Not Met",
        "Excellent performance. Your results have been saved.",
        "You did not meet the minimum speed or accuracy for this lesson.",
        "Net Speed",
        "Duration",
        "Total Chars",
        "Required Thresholds",
        "Speed",
        "Saving...",
        "Try Again",
        "Back to Lessons",
        "Leaderboard Coming Soon",
        "Compete with other typists to reach the top of the rankings.",
        "Rank",
        "Student",
        "No data available",
        "Best Speed",
        "Avg Accuracy",
        "Total Sessions",
        "Practice Time",
        "MINS",
        "Speed Progression (WPM)",
        "Accuracy Analysis (%)",
        "Daily Practice Volume",
        "My Enrolled Courses",
        "View details of the courses you are currently enrolled in.",
        "No Courses Allotted Yet",
        "You are not enrolled in any course yet. Please contact your center for enrollment.",
        "Enrolled",
        "Course",
        "Admission",
        "Exam",
        "Course Description",
        "No description available for this course.",
        "Eligibility",
        "Track your attendance records for",
        "Present Days",
        "Absent Days",
        "Attendance %",
        "Attendance Calendar",
        "Present",
        "Absent",
        "Late",
        "Leave",
        "My Certificates",
        "Certificates issued to you.",
        "Search by course or certificate no...",
        "Download All (Single PDF)",
        "No certificates issued yet.",
        "Download",
        "View",
        "Certificate Preview",
        "View-only preview. Final printing is handled by the admin.",
        "Close",
        "Certificate No",
        "Issued On",
        "Note: This is a digital preview. Signed/stamped certificates are printed and provided by the admin. Students cannot download directly from here.",
        "All Students",
        "View and search students enrolled under your center.",
        "View all students registered across the system.",
        "Add Student",
        "Student Directory",
        "Search...",
        "Loading...",
        "No students found",
        "Name",
        "Username",
        "Personal Mobile",
        "Address",
        "Government ID",
        "Documents",
        "Status",
        "Actions",
        "Not Provided",
        "10th DMC",
        "Government ID Image",
        "Signature",
        "Active",
        "Disabled",
        "Edit",
        "Enable",
        "Disable",
        "Delete",
        "Are you sure you want to move this student to the recycle bin?",
        "Student moved to recycle bin",
        "Failed to delete student",
        "An error occurred",
        "Wallet",
        "Your center's wallet balance and royalty-adjusted credits.",
        "Recharge Wallet",
        "Enter the amount you want to add to your center wallet.",
        "Amount (INR)",
        "Minimum recharge amount: ₹100",
        "Processing...",
        "Proceed to Pay",
        "Payable Balance",
        "Total Credited",
        "Royalty",
        "Recent Wallet Transactions",
        "No transactions yet.",
        "Net",
        "Wallet recharged successfully!",
        "Payment verification failed",
        "Something went wrong with the payment",
        "Failed to create order",
        "Razorpay SDK failed to load. Are you online?",
        "Attendance Register",
        "Mark and manage student attendance for your center.",
        "Search students...",
        "Save All",
        "Student Name",
        "ID / Username",
        "P",
        "A",
        "L",
        "Failed to load students",
        "No attendance changes to save.",
        "Attendance saved successfully",
        "Failed to save attendance",
        "Dashboard",
        "Overview",
        "Revenue Summary",
        "Center Statistics",
        "Activity Logs",
        "CRM",
        "Enquiries",
        "Enquiry Pipeline",
        "Follow-up Reminders",
        "Student Leads",
        "Franchise Leads",
        "General Leads",
        "CMS",
        "Pages",
        "Slider",
        "Gallery",
        "Teachers",
        "Partners",
        "Downloads",
        "Verification Page",
        "Ticker",
        "Blogs",
        "News",
        "Admins Management",
        "Add New Admin",
        "Admin List",
        "My Center Profile",
        "Request Profile Update",
        "Certificate Assets",
        "Attendance Register",
        "Monthly Report",
        "All Centers",
        "Add New Center",
        "Center Requests",
        "Franchise Fees",
        "Center Wallets",
        "Manage Locations",
        "Recycle Bin",
        "All Students",
        "Approvals",
        "Student Certificates",
        "Certificate Approvals",
        "Document Requests",
        "Enrollment Reports",
        "Add Student",
        "Student Fees",
        "Apply Certificates",
        "Issue certificates",
        "Issue marksheets",
        "Live Classes",
        "Schedule Class",
        "Class History",
        "New Enquiries",
        "Follow-ups",
        "Converted Leads",
        "Internal Messages",
        "Center Announcements",
        "Academics",
        "Course Categories",
        "Courses",
        "Subjects",
        "Question Bank",
        "Subject Mapping",
        "Sessions",
        "Study Material",
        "Exam Blueprints",
        "Mock Tests",
        "Exam Engine V2",
        "Question Feedback",
        "Allotted Courses",
        "Course Subjects",
        "Course Materials",
        "Languages",
        "Lessons",
        "Typing Analytics",
        "Tests & Allotment",
        "Global Reports",
        "Student Reports",
        "Center Leaderboard",
        "Practice Now",
        "My History",
        "Exams",
        "Allot Exam",
        "Exam Papers",
        "Exam Results",
        "Exam V2 (Center)",
        "Practicals",
        "All Practicals",
        "Create Practical",
        "Submissions",
        "Finance",
        "Wallet Management",
        "Transactions",
        "Commission Reports",
        "Franchise Payments",
        "Wallet",
        "My Balance",
        "Payment History",
        "Progress Summary",
        "My Course",
        "Enrolled Course",
        "My Subjects",
        "Recorded Classes",
        "Join Class",
        "Class Schedule",
        "Assigned Practicals",
        "Submit Practical",
        "Submission History",
        "My Attendance",
        "My Certificates",
        "Download Certificate",
        "My Exams",
        "Pending Exams",
        "Payments",
        "Fee Details",
        "Notifications",
        "Announcements",
        "Messages",
        "Review Us",
        "Attachments",
        "Certificate templates",
        "Marksheet templates",
        "ID card template (design)",
        "Template designer",
        "Staff Management",
        "Add New Staff",
        "Staff List",
        "System",
        "System Settings",
        "Shop Management",
        "Role Permissions",
        "Translation Usage",
        "Notification Settings",
        "Disk & Storage",
        "Admin Certificate Assets",
        "Maintenance",
        "Workspace",
        "Search portal records, students, or settings...",
        "Appearance",
        "Light",
        "Dark",
        "System",
        "Auto",
        "Select Theme",
        "Account Management",
        "My Profile",
        "Settings",
        "Privacy",
        "logout",
        "Premium Model (City)",
        "Investment Includes:",
        "Brand Authorization License",
        "ERP Software Access (Lifetime)",
        "Marketing Design Assets",
        "Initial Staff Training",
        "Center Interior Guidance",
        "National Job Portal Access",
        "Download Fee Structure",
        "Fee Structure Not Available",
        "Meet the Requirements?",
        "If you have the space and the vision, we have the system. Apply today to secure your territory.",
        "Empowering Partners, Transforming Lives",
        "Join SCRE, the fastest growing network of skill-based computer training centers in India.",
        "Partner with Excellence",
        "Active Centers",
        "Years Experience",
        "Success Rate",
        "Engineered for Growth",
        "Our ecosystem is built on three pillars: Advanced Technology, Industry-Aligned Content, and Unmatched Support.",
        "Automation-First",
        "Our custom ERP handles everything from inquiry to certification, reducing your manual workload by 80%.",
        "Premium Content",
        "High-quality video lectures, lab manuals, and e-books updated every session to stay ahead of the curve.",
        "Profit Protection",
        "We offer territory exclusivity and a low-royalty model to ensure our partners remain the most profitable in their city.",
        "The Smart Comparison",
        "See how we stack up against traditional computer center models.",
        "Feature / Advantage",
        "Local Brands",
        "Cloud ERP & Automation",
        "ISO 9001:2015 Certification",
        "Optional",
        "100+ Industry Courses",
        "National Placement Portal",
        "Marketing & Branding Kit",
        "Low Royalty Structure",
        "Partner Success Stories",
        "Real feedback from entrepreneurs who transformed their local communities with SCREduc.",
        "Rajesh Kumar",
        "Jind Center",
        "Starting a center with SCREduc was the best decision. The ERP made my life so easy that I could focus entirely on marketing and growth. We reached 100 students in just 4 months.",
        "Meenakshi Sharma",
        "Rohtak Hub",
        "The brand value and government certifications helped us gain trust instantly. Parents in our city now recognize SCREduc as the standard for quality IT training.",
        "Ready to Join the Leaders?",
        "Don't just open a computer center. Build a scalable education business with India's most advanced network.",
        "Find Your Center",
        "Search by center name, code, city, state, or pincode and open the full center profile.",
        "Search by name / code / city / pincode...",
        "Loading centers…",
        "No centers found.",
        "Code",
        "Active",
        "View Center",
        "Courses",
        "Show more",
        "Application submitted! Our team will contact you within 24 hours.",
        "Failed to submit application. Please try again.",
        "An error occurred. Please try again later.",
        "Happy Centers",
        "Strategic HQ",
        "24-Hour Response Guarantee",
        "Ready to Lead the",
        "Digital Revolution?",
        "Join our network of 50+ successful centers. We are currently accepting applications for the 2026-27 academic session.",
        "Limited slots available per district to ensure territory protection.",
        "Why Apply Now?",
        "Exclusive territory rights for early applicants",
        "Special setup discount on premium center models",
        "Immediate access to our 2026-27 Marketing Kit",
        "Priority staff training and certification",
        "Application Form",
        "Phone",
        "Select Budget",
        "Space (Sq. Ft)",
        "Education/Business Experience",
        "Briefly describe your background...",
        "Submit Application",
        "By submitting, you agree to our Franchise Privacy Policy.",
        "Login successful! Redirecting...",
        "Security code sent to {{email}}",
        "Failed to send verification code",
        "An error occurred during login.",
        "Identity verified! Redirecting...",
        "Invalid or expired code",
        "Verification failed",
        "SCRE",
        "Partner Portal",
        "Access your center dashboard to manage students, exams, and operations with our integrated ERP system.",
        "Real-time Analytics",
        "Empowering educational leaders with the world's most intuitive management platform.",
        "Welcome Back",
        "Enter your credentials to access the portal.",
        "Username / ID",
        "Password",
        "Forgot?",
        "Authenticating...",
        "Login to Portal",
        "New center partner?",
        "Apply for Franchise",
        "Support ticket created! Our team will get back to you shortly.",
        "Failed to submit ticket.",
        "World-Class Support for Every Partner",
        "You're never alone in your journey. Our dedicated support ecosystem ensures your center runs smoothly, 24/7.",
        "Partner Success Center",
        "Submit Support Ticket",
        "Direct Support Channels",
        "Choose the method that works best for you. Our experts are standing by to help.",
        "WhatsApp Support",
        "Instant messaging for quick operational queries and technical help.",
        "Chat on WhatsApp",
        "Priority Hotline",
        "Direct voice support for urgent matters available Mon-Sat, 10am-6pm.",
        "Call +91 94663 17100",
        "Email Desk",
        "For formal requests, documentation, and non-urgent detailed queries.",
        "Raised a",
        "Support Ticket",
        "Have a complex issue? Our ticketing system ensures your query is tracked and resolved within 24-48 business hours.",
        "Automated Tracking",
        "Expert Resolution",
        "Center Name",
        "Center ID",
        "Subject",
        "Priority",
        "Low - General Inquiry",
        "Medium - Technical Issue",
        "High - Operational Blocker",
        "Issue Description",
        "Please provide details about your issue...",
        "Submitting...",
        "Submit Ticket",
        "What kind of marketing support do you provide?",
        "We provide a complete launch kit including digital graphics, banners, brochures, and flyers. We also run centralized social media campaigns and help you with local SEO to ensure students find your center.",
        "How do I get technical training for the ERP?",
        "Upon joining, we conduct a 2-day virtual onboarding session. Additionally, we have detailed video tutorials available in your partner portal, and our support team can do a 1-on-1 screen-share if needed.",
        "Is there a limit to how many support tickets I can raise?",
        "No, there is no limit. We are here to ensure your success. However, we encourage checking our knowledge base first for common technical issues.",
        "How often are course materials updated?",
        "Our curriculum team updates the content every 6 months to ensure we are aligned with current industry trends and software versions.",
        "Premium Education. Scalable Returns.",
        "Invest in a future-proof business model. SCREduc provides a high-growth platform with low overheads and maximum social impact.",
        "Investment Models",
        "Strategic packages designed for different city tiers and business scales. Choose your path to leadership.",
        "Village Hub",
        "Tier 3 / Rural Focus",
        "5-8 Computers",
        "400-600 Sq. Ft.",
        "Basic IT Suite",
        "Regional Support",
        "Select Model",
        "Recommended",
        "Town Center",
        "Tier 2 / Urban Focus",
        "10-15 Computers",
        "800-1200 Sq. Ft.",
        "Full Course Catalog",
        "Placement Hub",
        "Start Application",
        "Regional Hub",
        "District / Metro Focus",
        "20+ Computers",
        "1500+ Sq. Ft.",
        "Advanced Tech Lab",
        "Strategic HQ",
        "Explore Scope",
        "Profitability Index",
        "Sustainable Revenue Architecture",
        "Our model prioritizes early cash flow and long-term center stability through diverse revenue streams.",
        "Rapid ROI",
        "Targeted break-even within 8 to 14 months based on operational efficiency.",
        "Fee Streams",
        "Continuous income from monthly tuition, examinations, and certifications.",
        "Monthly Projection",
        "Student Base",
        "Avg. Tuition",
        "Gross Revenue",
        "OPEX (Est.)",
        "Net Profit",
        "Estimated / Month",
        "Asset Allocation",
        "Franchise Fee",
        "Infrastructure",
        "Market Launch",
        "Reserve Capital",
        "Apply Now — It's Free",
        "View Courses",
        "Microsoft",
        "Google",
        "Adobe",
        "Tally Solutions",
        "NSDC",
        "NIELIT",
        "PMKVY",
        "Skill India",
        "ISO Certified",
        "# 785/10 Main Bazar Jeweler Market , opposite N.R, Jeweler, Jind, Haryana 126102",
        "Mon - Fri: 10.00 am - 06.00 pm",
        "Verification Letter",
        "Enquiry Now",
        "Sir Chhotu Ram Education Pvt. Ltd.",
        "IT & Skill Education",
        "SIR CHHOTU RAM EDUCATION PVT. LTD.",
        "An ISO 9001-2015 Certified Organization",
        "Registered Under The Company ACT 2013 By The Ministry Of Corporate Affairs",
        "Ministry of Micro, Small & Medium Enterprises,",
        "Government of India",
        "Founded",
        "Students",
        "Courses",
        "Placements",
        "Available Programs",
        "Explore Courses",
        "Designed with structured learning, practical exposure and clear outcomes.",
        "Showing",
        "courses",
        "No courses found",
        "Try a different keyword or switch category.",
        "Reset Filters",
        "Details",
        "Enquire",
        "All",
        "Computer Labs",
        "Classrooms",
        "Events",
        "Placements",
        "Gallery",
        "Life at SCRE",
        "A visual journey of our training sessions, events, and student activities across SCRE centers.",
        "View Image",
        "Frequently Asked Questions",
        "Find answers to common questions about our courses, certifications, and franchise opportunities.",
        "No FAQs found at the moment.",
        "Still have questions?",
        "Contact Support",
        "Student Zone",
        "Access attendance, certificates, announcements, and typing practice.",
        "Use your student account to access your dashboard.",
        "Go to Login",
        "Certificates",
        "View and download your issued certificates.",
        "Typing Practice",
        "Practice your typing and track progress.",
        "Downloads &",
        "Resources",
        "Access official brochures, application forms, syllabus, and other important documents.",
        "Search documents...",
        "No documents found.",
        "Official document for reference and download.",
        "Size",
        "Type",
        "N/A",
        "FILE",
        "Download Resource",
        "Other Resources",
        "SCRE Verification",
        "Authenticating Credentials...",
        "Verification Failed",
        "Please ensure the registration number is correct or contact your study center for assistance.",
        "Status: Verified",
        "This document is authentic and registered in our database.",
        "Certificate No.",
        "Student Name",
        "Official Candidate",
        "Course",
        "Issued On",
        "AN ISO 9001-2015 CERTIFIED ORGANIZATION",
        "Student Shop",
        "Supporting student creativity and craftsmanship",
        "Search products...",
        "Loading Products...",
        "No products found",
        "Try adjusting your search or filters",
        "Latest",
        "Admissions Open 2026 – Apply Now for Certified Diploma & Skill Courses.",
        "Franchise Registration Open – Start Your Own Training Center Today.",
        "Students Trained",
        "Courses Offered",
        "Placements Done",
        "Years Experience",
        "Success Stories",
        "Our Students, Our Pride",
        "Be the first student to share your success story!",
        "Verified Student",
        "Computer Lab",
        "Modern air-conditioned labs with latest high-performance systems.",
        "Interactive Classroom",
        "Smart boards & interactive live sessions.",
        "Seminar Hall",
        "Guest lectures & industry workshops.",
        "Placement Drive",
        "Campus recruitment & mock interviews.",
        "Award Ceremony",
        "Celebrating student excellence.",
        "Experience Our Campus Life",
        "Explore our modern infrastructure, learning environment and student success moments.",
        "Ready to Start Your Career Journey?",
        "Don't wait! Admissions are open. Enroll now and take the first step towards a successful career in IT.",
        "Apply Now — Free Counseling",
        "📞 Call Us Now",
        "Please enter an valid phone number (10-15 digits)",
        "Failed to submit enquiry. Please try again.",
        "An error occurred. Please try again later.",
        "Search center by name or code...",
        "Select Center (Admin Default)",
        "Thank you! We'll contact you soon.",
        "Your Full Name",
        "Phone Number",
        "Email Address (Optional)",
        "Your Message (Optional)",
        "Knowledge Center",
        "Industry Insights",
        "For Future Professionals",
        "Stay ahead with expert-written articles covering technology, marketing, finance, design, and career development. Our research-driven content delivers practical insights, industry analysis, and real-world strategies to help you build skills, make informed decisions, and remain competitive in an evolving job market.",
        "Explore All Articles",
        "Featured Article",
        "Top IT Skills in 2026 You Must Learn",
        "A strategic breakdown of high-demand technical skills shaping the global employment market.",
        "Jan 12, 2026",
        "6 min read",
        "Read More",
        "Career Growth",
        "Web Development Roadmap for Students",
        "Step-by-step progression from beginner to full stack mastery.",
        "Design Industry",
        "Why Graphic Designing Is Future-Proof",
        "Understanding creative economy growth and demand trends.",
        "Building Futures at SCRE",
        "Students building their future with SCRE through quality education and industry-recognized certifications.",
        "Aman Kumar",
        "Digital Marketing",
        "Priya Sharma",
        "Graphic Designing",
        "Rahul Singh",
        "Web Development",
        "Neha Verma",
        "Tally with GST",
        "Rohit Malik",
        "Computer Basics",
        "Sonia Gupta",
        "Data Entry",
        "Universities Joined with",
        "Partnering with recognized universities and institutions to deliver certified and industry-relevant education programs.",
        "Our Partners",
        "Partner 1",
        "Partner 2",
        "Partner 3",
        "Partner 4",
        "Partner 5",
        "Partner 6",
        "Our",
        "Partners",
        "Rajesh Verma",
        "Senior Web Development Trainer",
        "8+ Years Experience",
        "Neha Sharma",
        "Accounting & GST Expert",
        "6+ Years Experience",
        "Amit Kapoor",
        "Graphic Design Specialist",
        "7+ Years Experience",
        "Pooja Malik",
        "Spoken English Trainer",
        "5+ Years Experience",
        "Expert Trainer",
        "Our Faculty",
        "Meet Our Expert Trainers",
        "Our experienced faculty members bring real industry knowledge and practical expertise to ensure students receive career-focused training.",
        "Logged in successfully",
        "An error occurred during login"
    ];

    for key in static_keys {
        let translated = if lang == "en" {
            key.to_string()
        } else {
            get_translation(&db, key, &lang).await.unwrap_or_else(|_| key.to_string())
        };
        static_texts.insert(key.to_string(), translated);
    }

    // Fetch all collections
    let mut cms_items = Vec::new();
    if let Ok(mut cursor) = db.collection::<CMSItem>("cms_items").find(None, None).await {
        while let Some(Ok(mut item)) = cursor.next().await {
            if lang != "en" {
                item.title = get_translation(&db, &item.title, &lang).await.unwrap_or_else(|_| item.title);
                if let Some(d) = item.description {
                    item.description = Some(get_translation(&db, &d, &lang).await.unwrap_or_else(|_| d));
                }
                if let Some(c) = item.content {
                    item.content = Some(get_translation(&db, &c, &lang).await.unwrap_or_else(|_| c));
                }
                if let Some(bt) = item.button_text {
                    item.button_text = Some(get_translation(&db, &bt, &lang).await.unwrap_or_else(|_| bt));
                }
                if let Some(t) = item.tag {
                    item.tag = Some(get_translation(&db, &t, &lang).await.unwrap_or_else(|_| t));
                }
                if let Some(h) = item.highlight {
                    item.highlight = Some(get_translation(&db, &h, &lang).await.unwrap_or_else(|_| h));
                }
            }
            cms_items.push(item);
        }
    }

    let mut blogs = Vec::new();
    // Filter blogs same as list_blogs: status=Published, published_at <= now OR not set/null
    let blog_filter = doc! {
        "status": "published",
        "$or": [
            { "published_at": { "$lte": Utc::now() } },
            { "published_at": { "$exists": false } },
            { "published_at": null }
        ]
    };
    if let Ok(mut cursor) = db.collection::<Blog>("blogs").find(blog_filter, None).await {
        while let Some(Ok(mut post)) = cursor.next().await {
            if lang != "en" {
                post.title = get_translation(&db, &post.title, &lang).await.unwrap_or_else(|_| post.title);
                post.content = get_translation(&db, &post.content, &lang).await.unwrap_or_else(|_| post.content);
                if let Some(mt) = post.meta_title {
                    post.meta_title = Some(get_translation(&db, &mt, &lang).await.unwrap_or_else(|_| mt));
                }
                if let Some(md) = post.meta_description {
                    post.meta_description = Some(get_translation(&db, &md, &lang).await.unwrap_or_else(|_| md));
                }
            }
            blogs.push(post);
        }
    }

    let mut news = Vec::new();
    if let Ok(mut cursor) = db.collection::<News>("news").find(None, None).await {
        while let Some(Ok(mut n)) = cursor.next().await {
            if lang != "en" {
                n.title = get_translation(&db, &n.title, &lang).await.unwrap_or_else(|_| n.title);
                n.content = get_translation(&db, &n.content, &lang).await.unwrap_or_else(|_| n.content);
                if let Some(mt) = n.meta_title {
                    n.meta_title = Some(get_translation(&db, &mt, &lang).await.unwrap_or_else(|_| mt));
                }
                if let Some(md) = n.meta_description {
                    n.meta_description = Some(get_translation(&db, &md, &lang).await.unwrap_or_else(|_| md));
                }
            }
            news.push(n);
        }
    }

    let mut courses = Vec::new();
    if let Ok(mut cursor) = db.collection::<Course>("courses").find(None, None).await {
        while let Some(Ok(mut c)) = cursor.next().await {
            if lang != "en" {
                c.course_name = get_translation(&db, &c.course_name, &lang).await.unwrap_or(c.course_name);
                if let Some(d) = c.description {
                    c.description = Some(get_translation(&db, &d, &lang).await.unwrap_or(d));
                }
                if let Some(s) = c.syllabus {
                    c.syllabus = Some(get_translation(&db, &s, &lang).await.unwrap_or(s));
                }
                if let Some(e) = c.eligibility {
                    c.eligibility = Some(get_translation(&db, &e, &lang).await.unwrap_or(e));
                }
            }
            courses.push(c);
        }
    }

    let mut categories = Vec::new();
    if let Ok(mut cursor) = db.collection::<CourseCategory>("course_categories").find(None, None).await {
        while let Some(Ok(mut c)) = cursor.next().await {
            if lang != "en" {
                c.name = get_translation(&db, &c.name, &lang).await.unwrap_or(c.name);
                if let Some(d) = c.description {
                    c.description = Some(get_translation(&db, &d, &lang).await.unwrap_or(d));
                }
            }
            categories.push(c);
        }
    }

    (StatusCode::OK, Json(TranslatedContentResponse {
        cms: cms_items,
        blogs,
        news,
        courses,
        categories,
        static_texts,
    }))
}

const MAX_TRANSLATE_CHARS: usize = 8192;

#[derive(Debug, Deserialize)]
pub struct TranslateRequest {
    pub text: String,
    /// Accept `target` or `target_lang` (frontend uses `target_lang`).
    #[serde(default, alias = "target_lang")]
    pub target: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct BulkTranslateRequest {
    pub text: String,
    pub languages: Vec<String>,
}

#[derive(Debug, Serialize)]
pub struct TranslateResponse {
    pub translated: String,
}

#[derive(Debug, Serialize)]
pub struct TranslateError {
    pub message: String,
}

fn infer_target_lang(payload_target: Option<&str>, headers: &HeaderMap) -> String {
    if let Some(target) = payload_target.filter(|v| !v.trim().is_empty()) {
        return normalize_lang(target);
    }

    if let Some(lang_header) = headers.get("Accept-Language").and_then(|v| v.to_str().ok()) {
        let first = lang_header.split(',').next().unwrap_or("en");
        return normalize_lang(first);
    }

    "en".to_string()
}

pub async fn translate_text(
    State(db): State<Database>,
    headers: HeaderMap,
    Json(payload): Json<TranslateRequest>,
) -> (StatusCode, Json<Value>) {
    let ip = client_ip(&headers);
    let limiter = IpRateLimit {
        limit: 40,
        window: Duration::from_secs(60),
    };
    if !check_rate_limit(&format!("translate:{ip}"), &limiter) {
        return (
            StatusCode::TOO_MANY_REQUESTS,
            Json(serde_json::json!(TranslateError {
                message: "Rate limit exceeded".to_string()
            })),
        );
    }

    let text = payload.text.trim().to_string();
    if text.is_empty() {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!(TranslateError {
                message: "Text is required".to_string()
            })),
        );
    }
    if text.chars().count() > MAX_TRANSLATE_CHARS {
        return (
            StatusCode::PAYLOAD_TOO_LARGE,
            Json(serde_json::json!(TranslateError {
                message: format!("Text exceeds maximum length ({MAX_TRANSLATE_CHARS} characters)")
            })),
        );
    }

    let target = infer_target_lang(payload.target.as_deref(), &headers);
    if target == "en" {
        return (
            StatusCode::OK,
            Json(serde_json::json!(TranslateResponse { translated: text })),
        );
    }

    match get_translation(&db, &text, &target).await {
        Ok(translated) => (
            StatusCode::OK,
            Json(serde_json::json!(TranslateResponse { translated })),
        ),
        Err(message) => (
            StatusCode::BAD_GATEWAY,
            Json(serde_json::json!(TranslateError { message })),
        ),
    }
}

pub async fn translate_bulk(
    State(db): State<Database>,
    headers: HeaderMap,
    Json(payload): Json<BulkTranslateRequest>,
) -> (StatusCode, Json<Value>) {
    let ip = client_ip(&headers);
    let limiter = IpRateLimit {
        limit: 25,
        window: Duration::from_secs(60),
    };
    if !check_rate_limit(&format!("translate_bulk:{ip}"), &limiter) {
        return (
            StatusCode::TOO_MANY_REQUESTS,
            Json(serde_json::json!(TranslateError {
                message: "Rate limit exceeded".to_string()
            })),
        );
    }

    let text = payload.text.trim().to_string();
    if text.is_empty() {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!(TranslateError {
                message: "Text is required".to_string()
            })),
        );
    }
    if text.chars().count() > MAX_TRANSLATE_CHARS {
        return (
            StatusCode::PAYLOAD_TOO_LARGE,
            Json(serde_json::json!(TranslateError {
                message: format!("Text exceeds maximum length ({MAX_TRANSLATE_CHARS} characters)")
            })),
        );
    }
    if payload.languages.is_empty() {
        return (
            StatusCode::BAD_REQUEST,
            Json(serde_json::json!(TranslateError {
                message: "languages[] is required".to_string()
            })),
        );
    }

    let supported = get_supported_languages();
    let langs: Vec<String> = payload
        .languages
        .iter()
        .map(|l| normalize_lang(l))
        .filter(|l| supported.contains(&l.as_str()))
        .collect();

    let out = bulk_translate(&db, &text, &langs).await;
    (StatusCode::OK, Json(serde_json::json!(out)))
}
